mods.immersiveengineering.metal_press.removeAll()
mods.immersiveengineering.alloy_kiln.removeAll()
mods.immersiveengineering.arc_furnace.removeAll()
mods.immersiveengineering.blueprint_crafting.removeAll()
mods.immersiveengineering.bottling_machine.removeAll()
mods.immersiveengineering.crusher.removeAll()
mods.immersiveengineering.fermenter.removeAll()
mods.immersiveengineering.mixer.removeAll()
mods.immersiveengineering.refinery.removeAll()
mods.immersiveengineering.squeezer.removeAll()

mods.immersivepetroleum.distillation.removeAll()

mods.immersivetech.boiler.removeAll()
mods.immersivetech.boiler_fuel.removeAll()
mods.immersivetech.cooling_tower.removeAll()
mods.immersivetech.distiller.removeAll()
mods.immersivetech.electrolytic_crucible_battery.removeAll()
mods.immersivetech.gas_turbine.removeAll()
mods.immersivetech.heat_exchanger.removeAll()
mods.immersivetech.high_pressure_steam_turbine.removeAll()
mods.immersivetech.melting_crucible.streamRecipes()
mods.immersivetech.radiator.removeAll()
mods.immersivetech.solar_tower.removeAll()
mods.immersivetech.steam_turbine.removeAll()
