recipemap('assembler').recipeBuilder()
        .fluidInputs(liquid('redstone') * 144)
        .inputs(item('gregtech:meta_wire_fine', 112) * 4,item('gregtech:machine', 986), item('gregtech:meta_item_1', 217), item('gregtech:meta_item_1', 232))
        .outputs(item('immersiveengineering:metal_decoration0', 3) * 2)
        .duration(50)
        .EUt(256)
        .buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(liquid('plastic') * 288)
        .inputs(item('gregtech:wire_single', 112) * 4, item('gregtech:meta_plate', 51) * 5)
        .outputs(item('immersiveengineering:material', 8) * 5)
        .duration(80)
        .EUt(256)
        .buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(liquid('plastic') * 288)
        .inputs(item('gregtech:wire_single', 25) * 4, item('gregtech:meta_plate', 324) * 5)
        .outputs(item('immersiveengineering:material', 9) * 5)
        .duration(160)
        .EUt(256)
        .buildAndRegister()

recipemap('assembler').recipeBuilder()
        .fluidInputs(liquid('soldering_alloy') * 72)
        .inputs(item('gregtech:meta_plate', 51) * 2,item('gregtech:machine', 986), item('gregtech:meta_item_1', 127) * 4)
        .outputs(item('immersiveengineering:metal_decoration0', 4) * 2)
        .duration(50)
        .EUt(256)
        .buildAndRegister()
 
recipemap('assembler').recipeBuilder()
        .fluidInputs(liquid('steel') * 576)
        .inputs(item('immersiveengineering:metal_decoration0', 4), item('gregtech:meta_item_1', 172) * 4, item('gregtech:meta_plate', 324) * 2)
        .outputs(item('immersiveengineering:metal_decoration0', 5) * 2)
        .duration(50)
        .EUt(256)
        .buildAndRegister()
 
recipemap('assembler').recipeBuilder()
        .fluidInputs(liquid('iron') * 288)
        .inputs(item('gregtech:meta_plate', 51) * 2)
        .outputs(item('immersiveengineering:sheetmetal', 9) * 3)
        .duration(10)
        .EUt(4)
        .buildAndRegister()
 
recipemap('assembler').recipeBuilder()
        .fluidInputs(liquid('soldering_alloy') * 72)
        .inputs(item('gregtech:machine', 987), item('gregtech:meta_item_1', 128), item('gregtech:meta_item_1', 143),item('gregtech:wire_single', 25) * 2, ore('circuitMv' * 2))
        .outputs(item('immersiveengineering:metal_decoration0', 7) * 2)
        .duration(50)
        .EUt(256)
        .buildAndRegister()
 
recipemap('assembler').recipeBuilder()
        .fluidInputs(liquid('soldering_alloy') * 72)
        .inputs(item('immersiveengineering:metal_device1', 2), item('gregtech:wire_single', 25) * 4, ore('circuitMv'), item('gregtech:meta_plate', 25))
        .outputs(item('immersiveengineering:metal_decoration0', 6) * 2)
        .duration(50)
        .EUt(256)
        .buildAndRegister()
